version: "3.9"
services:
    web:
        build:
            context: .
            args:
                SECRET_KEY: ${SECRET_KEY}
        image: ticketmanager:latest
        ports:
            - "8000:8000"
