# Generated by Django 3.2.9 on 2023-01-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(max_length=300)),
                ('status', models.TextField(choices=[('Opened', 'Opened'), ('Closed', 'Closed')], default='Opened')),
                ('assigned_to', models.CharField(default='Unassigned', max_length=30)),
                ('opened_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=30)),
            ],
        ),
    ]
