# Generated by Django 3.2.9 on 2023-01-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.TextField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Opened'),
        ),
    ]
